/**
 * RO Tools Changelog
 *
 * Add new entries at the TOP of the array when shipping features.
 * This file is the single source of truth for the Updates page.
 *
 * Categories: new_feature | improvement | bug_fix | announcement
 */

export const changelog = [
  // ── v2.9.3 — April 3, 2026 ───────────────────────────────────────
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Feature Request Priority and Category Not Submitted',
    description: 'The Support page showed priority and category dropdowns for feature requests (RT-232) but never included those fields in the API call. Both fields are now sent and stored with each ticket.',
  },
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Auth Bypass in Employee Document API Routes',
    description: 'The /api/employees and /api/employees/documents routes were checking only whether a session cookie existed, not whether it was valid. Any request with any cookie value would pass authentication. Both routes now use getSession() which properly verifies the token.',
  },
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Wrong Manager Name Saved to Employee Document Records',
    description: 'The coaching-form and evaluation generators were saving the wrong field as "createdBy" in the employee document record — referencing supervisorName/managerName fields that do not exist in those forms. Fixed to use coachName for coaching forms and evaluatorName for evaluations.',
  },
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Broken Re-Generate Links for Flyer and Training Documents',
    description: 'The History page "Re-generate" button linked to /dashboard/generators/training-level1 and similar paths that do not exist. Flyer re-generates now go to /dashboard/flyer and all training types go to /dashboard/documents with the correct template pre-selected.',
  },
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Stale Closure in Flyer and Documents Ctrl+Enter Handlers',
    description: 'The Catering Flyer and Documents pages registered their keyboard handlers with outdated references to handleDownload. Ctrl+Enter would use stale form data if fields were changed after mount. Both pages now correctly track the latest handler.',
  },
  {
    version: 'v2.9.3',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Store Count Updated to 30+',
    description: 'The dashboard home page showed "29+ locations" in two places but JMVG has 30 stores. Updated to 30+.',
  },
  // ── v2.9.2 — April 4, 2026 ───────────────────────────────────────
  {
    version: 'v2.9.2',
    date: '2026-04-04',
    category: 'improvement',
    title: 'Ctrl+Enter Keyboard Shortcut Now Works in All 15 Generators',
    description: 'Every generator showed "Tip: Press Ctrl+Enter to generate" but only Written Warning actually had it wired up. The shortcut is now functional in all 15 generators. Also removed a redundant global handler in layout.js that would have double-triggered PDF generation.',
  },
  {
    version: 'v2.9.2',
    date: '2026-04-04',
    category: 'improvement',
    title: 'Save to Drive Added to 5 More Generators',
    description: 'Food Labels, Manager Log, Onboarding Packets, Work Orders, and DM Walk-Through were the only generators missing the Save to Drive button. All five now have it.',
  },
  {
    version: 'v2.9.2',
    date: '2026-04-04',
    category: 'bug_fix',
    title: 'Directives Scorecard Default Month Is Now Dynamic',
    description: 'The Monthly Scorecard on the Directives page defaulted to "April 2026" hardcoded. It now defaults to the current month so it automatically shows the right period.',
  },
  {
    version: 'v2.9.2',
    date: '2026-04-04',
    category: 'bug_fix',
    title: 'Scoreboard Disclaimer Updated to 12 Weeks',
    description: 'The scoreboard data note said "Weeks 1-11 (Dec 29 - Mar 15)" but Week 12 data (Mar 16-22) has been loaded. Updated to reflect all 12 weeks.',
  },
  {
    version: 'v2.9.2',
    date: '2026-04-04',
    category: 'bug_fix',
    title: 'Fix Auth Bypass in Directives API',
    description: 'The /api/directives and /api/directives/outreach routes defined a local async getSession() but called it without await. A Promise is always truthy so the auth check never rejected unauthenticated requests. Fixed.',
  },
  // ── v2.9.1 — April 3, 2026 ───────────────────────────────────────
  {
    version: 'v2.9.1',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Missing --text CSS Variable Now Defined',
    description: 'The --text CSS variable was referenced in the Directives, Reading, Scoreboard, and Setup pages but was never defined in globals.css. Text in those sections was inheriting browser default color instead of the app charcoal. Fixed.',
  },
  {
    version: 'v2.9.1',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Stale Closure Bugs in 3 More Generators',
    description: 'Coaching Form, Injury Report, and Performance Evaluation had [form.employeeName] as useCallback deps instead of [form], causing stale data to be included in PDFs when the form was updated after the callback was created.',
  },
  {
    version: 'v2.9.1',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Scoreboard Stat on Landing Page Updated to 12 Weeks',
    description: 'The landing page showed "11 Weeks" for the scoreboard feature card. Updated to reflect the actual 12 weeks of data available.',
  },
  {
    version: 'v2.9.1',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Performance Evaluation Now Shows Store Number in PDF',
    description: 'The evaluation PDF preview now shows store number alongside the store name (e.g., "Jersey Mike\'s #20360 (#20360)"). Previously, only the store name was shown.',
  },
  {
    version: 'v2.9.1',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Quick Tour Generator Count Fixed (12 → 15)',
    description: 'The Quick Tour shown to new users still said "12 professional PDF generators." Updated to 15.',
  },
  // ── v2.9.0 — April 3, 2026 ───────────────────────────────────────
  {
    version: 'v2.9.0',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'History Page Action Filter Now Uses Server-Side Filtering',
    description: 'The action filter (Download / Drive Save / Email) in Document History was filtering only the current page of results, making totals and pagination wrong. Now filters server-side so counts and pages are accurate.',
  },
  {
    version: 'v2.9.0',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Dashboard Recent Activity — Correct Links for Flyer & Training Docs',
    description: 'Clicking "Open →" on a Catering Flyer or Training Document in the Recent Activity feed was 404ing. Fixed: flyer links to /dashboard/flyer and all training types link to /dashboard/documents.',
  },
  {
    version: 'v2.9.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Catering Flyer Added to Navbar Catering Dropdown',
    description: 'The Catering Flyer generator was buried in the Generators page and not accessible from the main nav. Added it to the Catering dropdown on both desktop and mobile.',
  },
  {
    version: 'v2.9.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Updates Page Clears Notification Bell on Visit',
    description: 'Visiting the Updates & Changelog page now marks updates as read, clearing the red dot from the notification bell in the Navbar.',
  },
  {
    version: 'v2.9.0',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Store Number Now Editable in Store Profile',
    description: 'Store number was set during initial setup but could not be changed from the Store Profile page. Added as an editable field.',
  },
  // ── v2.8.0 — April 3, 2026 ───────────────────────────────────────
  {
    version: 'v2.8.0',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Fix Dashboard Activity Feed (API Route Correction)',
    description: 'The dashboard home was calling a non-existent /api/audit route, so "Recently Generated" always showed empty. Fixed to /api/logs. Feed now shows real data.',
  },
  {
    version: 'v2.8.0',
    date: '2026-04-03',
    category: 'new_feature',
    title: 'Notification Bell Now Works',
    description: 'Created /api/updates which returns changelog entries. The Updates bell in the Navbar notification dot now correctly lights up when new updates are available.',
  },
  {
    version: 'v2.8.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Documents Page — Draft Persistence + EmployeeSelect + Ctrl+Enter',
    description: 'Training Documents page now auto-saves your selected template and employee name across page loads. Employee name field uses the searchable EmployeeSelect component. Added Ctrl+Enter shortcut and success state.',
  },
  {
    version: 'v2.8.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Inline Validation Errors on 4 More Generators',
    description: 'meal-break-waiver, attestation-correction, timesheet-correction, and onboarding-packets now show red error messages under the Employee Name field when empty, clearing automatically when filled.',
  },
  {
    version: 'v2.8.0',
    date: '2026-04-03',
    category: 'bug_fix',
    title: 'Generator Count Updated to 15 Across All Pages',
    description: 'Landing page, dashboard overview, and Built for Operators section all showed stale "12 generators" count. Now corrected to 15. Training templates updated from 5 to 8.',
  },
  // ── v2.7.0 — April 3, 2026 ───────────────────────────────────────
  {
    version: 'v2.7.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Character Counts + Start Over on All Generators',
    description: 'All generator text areas now show live character counts with limits (400–800 chars depending on field). Added a "↺ Start over" button to all 15 generators that clears the auto-saved draft and resets the form. History page now recognizes all 15 generator types and gained a one-click "Clear filters" button.',
  },
  {
    version: 'v2.7.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Generator Auto-Save Drafts',
    description: 'All 15 document generators now auto-save your work to browser storage. If you navigate away or close the tab, your draft is restored when you return. Drafts expire after 7 days. Generator cards show a "draft" badge when a saved draft is available.',
  },
  {
    version: 'v2.7.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Preview Zoom Controls on All Generators',
    description: 'Added zoom in/out/reset controls to the Live Preview panel on all 15 generators, making it easier to inspect dense documents like termination forms, evaluations, and compliance waivers.',
  },
  {
    version: 'v2.7.0',
    date: '2026-04-03',
    category: 'improvement',
    title: 'Download Button Polish + Keyboard Shortcut Help',
    description: 'Download buttons now show an animated spinner while generating and a green ✓ confirmation after success. Added "Ctrl+Enter to download" hint text on all generator pages. Press ? on any page to see a keyboard shortcut reference overlay.',
  },

  // ── v2.6.0 — March 28, 2026 ──────────────────────────────────────
  {
    version: 'v2.6.0',
    date: '2026-03-28',
    category: 'new_feature',
    title: 'RO Tools iOS App',
    description: 'Native iOS app for iPhone and iPad. All 12 document generators with on-device PDF rendering, 54-page training packets, catering CRM with push notification reminders, live scoreboard, offline support with background sync, and Google OAuth login restricted to @jmvalley.com. Available on TestFlight.',
  },
  {
    version: 'v2.6.0',
    date: '2026-03-28',
    category: 'improvement',
    title: 'Week 12 Scoreboard + UI Refresh',
    description: 'Added Week 12 data (Mar 16-22, 29 stores). Overview page expanded with "Why RO Tools" section, By the Numbers stats, and red accent balance. Active tab highlighting in navbar, branded red scrollbar, red overscroll effect, and Dashboard renamed to Overview.',
  },

  // ── v2.5.0 — March 27, 2026 ──────────────────────────────────────
  {
    version: 'v2.5.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Full Training Packet Rebuild — 54 Pages from Director\'s Source PDFs',
    description: 'Complete rebuild of all training documents from the Director\'s original source materials. Every checkbox, training list, benchmark, GM debrief, certification criteria, LMS video reference, and quality check from the originals is now included. Multi-page PDF generation with page numbers on every page.',
  },
  {
    version: 'v2.5.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Orientation Packet (New)',
    description: 'Brand new standalone Day 1 Orientation document — 5 pages covering policies, procedures, daily operations, guest service, store policies, team player values, JMVG core values, and LMS video assignments. Extracted from Level 1 as its own template.',
  },
  {
    version: 'v2.5.0',
    date: '2026-03-27',
    category: 'improvement',
    title: 'Multi-Page PDF Support',
    description: 'Documents page now supports multi-page PDF generation. Each page is captured independently and assembled into a single PDF with addPage. All 8 training templates generate true multi-page documents matching the Director\'s originals.',
  },

  // ── v2.4.0 — March 27, 2026 ──────────────────────────────────────
  {
    version: 'v2.4.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Employee Resignation Form',
    description: 'Full resignation documentation with resignation type (Voluntary, Job Abandonment, Mutual Agreement), notice period tracking, equipment return checklist, exit interview status, and final pay information.',
  },
  {
    version: 'v2.4.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Employee Termination Form',
    description: 'Comprehensive termination documentation with termination type, prior discipline history, final pay per California Labor Code §201-202, company property return checklist, witness signature, and COBRA/benefits notes.',
  },
  {
    version: 'v2.4.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Meal Break Waiver',
    description: 'California-compliant meal period waiver agreement per Labor Code §512 and IWC Order No. 5-2001. Supports first meal, second meal, and on-duty meal period waivers with full legal acknowledgments and revocation notice.',
  },
  {
    version: 'v2.4.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Demo Mode',
    description: 'Visit ro-tools.app/demo for a read-only demo session. Pre-seeded with sample store data, users, tickets, and activity logs. No @jmvalley.com account required. 2-hour sessions.',
  },
  {
    version: 'v2.4.0',
    date: '2026-03-27',
    category: 'new_feature',
    title: 'Self-Playing Presentation',
    description: 'Auto-advancing presentation at ro-tools.app/presentation with 14 slides covering the full platform, ROI data, compliance, and roadmap. Keyboard navigation and progress bar.',
  },

  // ── v2.3.0 — March 26, 2026 ──────────────────────────────────────
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'JMVG Scoreboard',
    description: 'Full scoreboard with all 11 weeks of data. Leaderboards for Grand Slams (4/4 targets), Trifectas (3+ targets), and Highest Avg Growth %. Weekly view with color-coded performance (Royal Blue, Blue, Green, Yellow, Orange). Store names displayed throughout.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Store Directory & Auto-Setup',
    description: 'All 29 JMVG stores mapped with names, RO assignments, and DM districts. DMs get their stores auto-populated on first login. Predictive store number search on setup page.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Marketing Directives Page',
    description: 'Rebuilt directives page with real JMVG data: April monthly marketing directive, ALL RO Meeting recap with action items, key dates, and the full 2026 marketing calendar.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Catering Tracker Enhancements',
    description: 'Upcoming Events widget showing notable dates in next 30 days. Generate Order button pre-fills catering form with client info. Next Expected Order date column. Reorder button re-loads past orders into the form.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Landing Page Rebuild',
    description: 'Full redesign with 6 tool cards (all live), stats bar, updated hero section showcasing the complete platform. Jersey Mike\'s logo on catering flyer.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'PDF Generator Standardization',
    description: 'All 7 generators and the catering flyer now use consistent header/footer styling: red bar, JMVG logo, blue dividers, standardized spacing.',
  },
  {
    version: 'v2.3.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'OAuth & Security',
    description: 'Removed "Google hasn\'t verified this app" warning. Login now uses basic scopes only. Drive/Gmail access granted incrementally when needed. Connected Services management in profile.',
  },

  // ── v2.2.0 — March 26, 2026 ──────────────────────────────────────
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Admin Activity Logs',
    description: 'New Activity Logs tab in the Admin Panel. Search by name, email, or document. Filter by generator type and action (download, Drive save, email). Paginated table with color-coded action badges.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: '3 New Training Packets',
    description: 'Added Slicer Training (4-week certification), Opener Training (opening shift certification), and Shift Lead Training (leadership & closing certification). All 7 training packets now available under Documents.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Coaching Form & Injury Report Generators',
    description: 'Two new document generators: Coaching Form for documenting employee coaching sessions, and Injury Report for workplace incident documentation. Both produce branded PDFs with auto-filled store info.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Activity Logging System',
    description: 'All document generation actions (download, Drive save, email) are now logged with user info, generator type, form data, and timestamps. Powers the new admin Activity Logs tab.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Training Packet Uniformity Overhaul',
    description: 'Enterprise-level standardization across all 7 training packets. Identical employee info blocks, centered logo, consistent fonts (6.5pt body, 8pt headers, 9pt values), uniform sign-off sections, and standardized checkbox sizing.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Catering Order Enhancements',
    description: 'Added bread selection (White, Wheat, Rosemary) per sub in catering orders. Cookie and Brownie platter lines now always visible in the order form and PDF, even when quantity is zero.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Navigation & Profile Cleanup',
    description: 'Moved Generation History link from the main navbar into the Store Profile page for a cleaner navigation bar.',
  },
  {
    version: 'v2.2.0',
    date: '2026-03-26',
    category: 'bug_fix',
    title: 'Document Template Content Cutoff Fix',
    description: 'Fixed training packets and other documents where content was cut off at the bottom or overlapped by the footer. Separated content area from flex spacer and added proper footer margin spacing.',
  },

  // ── v2.1.0 — March 26, 2026 ──────────────────────────────────────
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Save to Google Drive',
    description: 'All generators now include a "Save to Google Drive" button with a folder picker. Browse your Drive, create new folders, and save generated PDFs directly into any location — like an employee file.',
  },
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Training Documents Generator',
    description: 'New Documents page with 4 branded templates: Level 1 (Day 1 Orientation), Level 2 (Cold Side Cert), Level 3 (Hot Side Cert), and New Hire Checklist. All share a uniform JMVG document template with red bars, blue headers, and logo.',
  },
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Privacy Policy & Terms of Service',
    description: 'Added public /privacy and /terms pages required for Google OAuth verification. Covers data handling, Drive access, and user rights.',
  },
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'JMVG Logo Branding Overhaul',
    description: 'Replaced all instances of the old NFL x JM logo with the official JMVG transparent-background logo. Updated navbar, landing page, footer, favicon, flyer preview, catering order, and all generator preview components.',
  },
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'improvement',
    title: 'Uniform Document Branding',
    description: 'All generated PDFs now feature consistent JMVG branding: top red accent bar, centered logo, store info line, blue title banner, and footer. Applied to all 4 generator preview components (Written Warning, Evaluation, Timesheet Correction, Attestation Correction).',
  },
  {
    version: 'v2.1.0',
    date: '2026-03-26',
    category: 'new_feature',
    title: 'Custom Domain: ro-tools.app',
    description: 'Connected ro-tools.app domain via Cloudflare DNS pointing to Cloud Run. SSL certificate provisioned. OAuth redirect URIs updated for the new domain.',
  },

  // ── v2.0.0 — March 25, 2026 ──────────────────────────────────────
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'new_feature',
    title: '5 New Document Generators',
    description: 'Written Warning, Performance Evaluation, Catering Order Form, Timesheet Correction, and Attestation Correction. All generators produce uniform, branded PDFs with auto-filled store info.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'new_feature',
    title: 'Directives Page',
    description: 'New standalone Directives page with the 2026 Marketing Calendar showing quarterly focus areas and monthly campaigns.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'new_feature',
    title: 'Service Account Integration',
    description: 'Google Drive, Sheets, and Docs accessible via service account. Drive scanner endpoint for file discovery and document content reading.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'Enterprise Security Audit',
    description: 'HMAC-SHA256 signed session cookies, rate limiting on all API routes, input sanitization, API timeouts, audit logging, role escalation prevention, and CSRF protection.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: '10-Breakpoint Responsive System',
    description: 'Full responsive redesign from 1024px down to 360px across every page and component. Mobile hamburger menu with slide-out navigation. Fluid scaling with no overflow on any device.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'Toast Notifications',
    description: 'New toast notification system replaces all browser alert() dialogs. Non-intrusive, auto-dismissing success/error/info toasts.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'CSS Variables & Theming',
    description: 'Replaced all hardcoded color hex values with CSS custom properties for consistent brand theming across the entire app.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'Error Boundaries',
    description: 'Added ErrorBoundary component wrapping all dashboard pages. Individual page crashes no longer break the entire app.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'Navigation Restructure',
    description: 'Reorganized navigation to 6 main tabs with dropdown menus for Generators. Support moved to icon in top-right corner. All generators accessible from navbar dropdown.',
  },
  {
    version: 'v2.0.0',
    date: '2026-03-25',
    category: 'improvement',
    title: 'GitHub Actions CI/CD',
    description: 'Added GitHub Actions deploy workflow as an alternative to Cloud Build. Automated build and deploy to Cloud Run on push to main.',
  },

  // ── v1.1.0 — March 25, 2026 ──────────────────────────────────────
  {
    version: 'v1.1.0',
    date: '2026-03-25',
    category: 'new_feature',
    title: 'Updates & Changelog Page',
    description: 'Added a changelog page so operators can see what\'s new. Timeline view of all development updates with version tags and categories.',
  },

  // ── v1.0.0 — March 24, 2026 ──────────────────────────────────────
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Google Drive, Sheets & Docs Integration',
    description: 'Connected Google Drive, Sheets, and Docs APIs for reading shared files and future automated document generation.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Cloud Build Auto-Deploy',
    description: 'Configured Cloud Build to auto-deploy to Cloud Run on every push to main. Zero-touch deployment pipeline.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Native Google OAuth',
    description: 'Secure login restricted to @jmvalley.com accounts. Replaced initial Firebase auth with native Google OAuth 2.0 via googleapis. Domain-restricted for franchise security.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Catering Flyer Generator',
    description: 'Generate print-ready catering flyers with store info, full 16-item catering menu, and pricing. Download as letter-size PDF.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Store Profile Management',
    description: 'Operators can set and edit their store details — address, phone, operator name, assistant info. Profile data auto-fills into all generated documents.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Role-Based Onboarding',
    description: 'First-time login setup flow. Choose your role (Operator, District Manager, Administrator) and enter store info. DM and Admin roles require super admin approval.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Admin Panel',
    description: 'User management and role approval dashboard for super admins. View all users, approve or deny role requests, manage access.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'new_feature',
    title: 'Support Page',
    description: 'Bug report and feature request forms. Submissions stored server-side and visible to the submitting user for tracking.',
  },
  {
    version: 'v1.0.0',
    date: '2026-03-24',
    category: 'announcement',
    title: 'RO Tools Launched',
    description: 'Initial deployment to Google Cloud Run. Full Next.js 14 app with dashboard, navigation framework, and JM Valley Group branding. Built from the ground up for franchise operators.',
  },
];
