'use client';

const BLUE = '#134A7C';
const RED = '#EE3227';
const NAVY = '#0d2d4a';

const PROTECTIONS = [
  {
    title: 'Tamper-Evident Document Storage',
    category: 'Integrity',
    color: '#1a5a94',
    desc: 'Every document generated by RO Tools — written warnings, termination letters, injury reports, meal break waivers — is stored in immutable GCS buckets with object versioning enabled. Once saved, a document cannot be altered without creating an audit record. This is the difference between a document that holds up in court and one that doesn\'t.',
    protects: 'Protects against post-dispute document alteration claims',
  },
  {
    title: 'Timestamped Digital Signatures',
    category: 'E-Signature',
    color: '#2d7a4a',
    desc: 'Every signature captured through RO Tools is attached to a server-generated ISO 8601 timestamp, the signer\'s verified @jmvalley.com identity, and the document version hash. Signatures cannot be backdated. This creates a legally defensible signing record for all 30 JMVG locations.',
    protects: 'Protects against "I never signed that" or "that\'s not my signature" disputes',
  },
  {
    title: 'California Meal Break Attestation',
    category: 'CA §226.7 / §512',
    color: '#8e44ad',
    desc: 'Under California Labor Code §226.7, an employer must pay a premium for any missed, short, or interrupted meal break — unless a valid waiver is on file. RO Control captures a signed attestation from every crew member at clock-out, every shift, confirming their meal break was taken. This closes a $10,000+ per-incident gap that most operators leave open.',
    protects: 'Protects against DLSE missed-meal-premium claims across all 30 locations',
  },
  {
    title: 'PIN-Verified Timeclock with Store Geofence',
    category: 'Timeclock Integrity',
    color: '#d35400',
    desc: 'Every clock-in and clock-out in RO Control requires a 4–6 digit PIN entered at the in-store kiosk. Punches are logged with device IP, user ID, and a server-side timestamp. There is no mobile clock-in — no employee can punch in from home. This eliminates time fraud liability and makes every labor record independently verifiable.',
    protects: 'Protects against time fraud, buddy-punching, and disputed timesheet claims',
  },
  {
    title: 'HR Document Generation with Legal Compliance',
    category: 'California Labor Law',
    color: '#c0392b',
    desc: 'RO Tools\' 17 document generators enforce required fields for every California-specific form: termination notices include WARN Act acknowledgments, written warnings include appeal process language, injury reports include OSHA 300 log requirements, and meal break waivers include CA-required mutual-consent language. A form cannot be submitted with missing required fields.',
    protects: 'Protects against defective-document claims that void disciplinary actions or create liability',
  },
  {
    title: 'Full Structured Audit Log',
    category: 'Chain of Custody',
    color: '#1a5a94',
    desc: 'Every action taken in RO Tools and RO Control — logins, document generations, form submissions, profile edits, admin approvals, clock events — is written to a structured JSONL audit log with user ID, store, IP, and timestamp. Logs are retained for 7 days in Cloud Logging and indefinitely in GCS. In any legal or regulatory investigation, JMVG can produce a complete chain of custody in minutes.',
    protects: 'Protects against "we don\'t know what happened" scenarios in HR disputes and OSHA inspections',
  },
  {
    title: 'OSHA-Compliant Injury Reports',
    category: 'OSHA 300 / 301',
    color: '#2d7a4a',
    desc: 'RO Tools generates OSHA Form 301-compatible injury reports with all required fields: nature of injury, body part, work environment, treatment received, and return-to-work status. Reports are timestamped, signed, and stored. JMVG can generate an OSHA 300 log summary from stored records at any time — without relying on paper forms or email threads.',
    protects: 'Protects against OSHA citation for failure to maintain injury and illness records',
  },
  {
    title: 'Role-Based Access Control',
    category: 'Access Control',
    color: '#8e44ad',
    desc: 'Every user in RO Tools and RO Control is assigned a verified role: Crew, Manager, District Manager, or Administrator. Access to sensitive functions — admin panels, payroll data, termination forms — is restricted by role and requires manager approval. No crew member can access HR documents. No manager can access another store\'s records.',
    protects: 'Protects against unauthorized access claims and privacy violations',
  },
];

const SCENARIOS = [
  {
    scenario: 'Wrongful Termination Claim',
    without: 'Termination letter was typed in Google Docs, modified after signing, no digital signature, no storage audit trail. JMVG cannot prove the document was signed or that it was not altered.',
    with: 'RO Tools generated the termination letter, captured a timestamped digital signature, stored it in immutable GCS. The signer\'s identity, device, and exact signing time are on record. The document cannot have been altered post-signature.',
  },
  {
    scenario: 'Missed Meal Break Premium Claim (CA §226.7)',
    without: 'No signed attestation on file. Employee claims they were denied a meal break. JMVG has no record. Under CA law, the burden of proof is on the employer. Default judgment: $10,000+ per incident.',
    with: 'RO Control captured a signed meal break attestation at clock-out. The crew member\'s PIN, timestamp, and statement are on record. JMVG presents the attestation and the claim is dismissed.',
  },
  {
    scenario: 'OSHA Workplace Injury Investigation',
    without: 'Injury was reported on a paper form, kept in a binder, stored at the store. Inspector arrives and the form is missing or incomplete. JMVG faces a citation for failure to maintain OSHA 300 records.',
    with: 'RO Tools generated an OSHA-compliant injury report at time of incident. The report is stored in GCS, accessible from any device. JMVG produces it in 30 seconds during an inspection.',
  },
  {
    scenario: 'Disputed Written Warning / Progressive Discipline',
    without: 'Employee disputes receiving the warning. Manager says they gave it. No proof — the Word doc may have been edited, email was deleted, and there\'s no signature on file. HR cannot defend the disciplinary record.',
    with: 'RO Tools generated the written warning, the employee signed it digitally at the store, and the signed document was stored immutably. JMVG shows the signature, timestamp, and store IP in the record.',
  },
  {
    scenario: 'Time Fraud / Buddy Punching Dispute',
    without: 'Homebase mobile punches allow clock-ins from anywhere. A terminated employee or their friend clocks someone in. JMVG cannot distinguish legitimate punches from fraudulent ones.',
    with: 'RO Control requires a PIN on a fixed kiosk. Every punch is IP-scoped to the store. There is no mobile clock-in. Fraudulent punches are structurally impossible.',
  },
];

export default function LiabilityPage() {
  return (
    <div style={{ fontFamily: "'DM Sans', sans-serif", background: '#f8fafc', color: '#1a1a2e', minHeight: '100vh' }}>

      {/* HERO */}
      <div style={{
        background: `linear-gradient(135deg, #1a0a2e 0%, #3d1a7a 50%, #6c3483 100%)`,
        padding: '80px 40px 90px',
        textAlign: 'center',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute', inset: 0,
          backgroundImage: 'radial-gradient(circle, rgba(255,255,255,0.04) 1px, transparent 1px)',
          backgroundSize: '32px 32px',
          pointerEvents: 'none',
        }} />
        <div style={{ position: 'relative', zIndex: 1, maxWidth: 820, margin: '0 auto' }}>
          <div style={{
            display: 'inline-block',
            background: 'rgba(200,150,255,0.2)',
            border: '1px solid rgba(200,150,255,0.4)',
            borderRadius: 100,
            padding: '6px 22px',
            fontSize: 12, fontWeight: 700, letterSpacing: 2.5,
            textTransform: 'uppercase', color: '#d7a8ff', marginBottom: 28,
          }}>
            Liability Protection Brief · April 2026
          </div>
          <h1 style={{
            fontSize: 'clamp(40px, 7vw, 80px)', fontWeight: 900,
            fontFamily: "'Playfair Display', serif",
            color: '#fff', lineHeight: 1.05, margin: '0 0 20px', letterSpacing: -2,
          }}>
            How RO Tools Protects <span style={{ color: '#c39bd3' }}>JMVG</span> from Liability
          </h1>
          <p style={{
            fontSize: 'clamp(15px, 2vw, 19px)', color: 'rgba(255,255,255,0.8)',
            maxWidth: 660, margin: '0 auto 44px', lineHeight: 1.6,
          }}>
            Full audit trails, tamper-evident document storage, digitally signed attestations, and automated compliance enforcement — protecting JM Valley Group from human-error liability across all 30 locations.
          </p>

          <div style={{ display: 'flex', gap: 24, justifyContent: 'center', flexWrap: 'wrap' }}>
            {[
              ['8', 'Liability Protections'],
              ['5', 'Real-World Scenarios Covered'],
              ['$0', 'DLSE Claims Defensible'],
              ['100%', 'Document Audit Trail'],
            ].map(([val, label]) => (
              <div key={label} style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 36, fontWeight: 900, color: '#d7a8ff', fontFamily: "'Playfair Display', serif" }}>{val}</div>
                <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.6)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1 }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 1000, margin: '0 auto', padding: '64px 32px 80px' }}>

        {/* INTRO */}
        <div style={{
          background: NAVY, borderRadius: 16, padding: '36px 40px', color: '#fff', marginBottom: 56,
        }}>
          <h2 style={{ fontSize: 20, fontWeight: 800, marginBottom: 12 }}>The Problem with Manual Processes</h2>
          <p style={{ opacity: 0.85, lineHeight: 1.7, fontSize: 15, marginBottom: 14 }}>
            In a franchise operation spanning 30 locations, the largest source of legal liability is not bad intent — it is inconsistency. A manager who forgets to get a signature. A form that was filled out wrong. A break that wasn't recorded. A document that was filed in the wrong folder. These errors, repeated across hundreds of employees and thousands of shifts, create a litigation surface that no franchise can fully defend.
          </p>
          <p style={{ opacity: 0.85, lineHeight: 1.7, fontSize: 15, marginBottom: 0 }}>
            RO Tools and RO Control are designed to make the right action the only action. Document generators enforce required fields. Timeclock requires physical PIN verification. Signatures are timestamped at the server level. Every event is logged. Human error is systematically reduced — and when it does occur, it is traceable.
          </p>
        </div>

        {/* PROTECTION CARDS */}
        <h2 style={{ fontSize: 13, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', color: '#999', marginBottom: 24 }}>
          8 Active Liability Protections
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(440px, 1fr))', gap: 20, marginBottom: 64 }}>
          {PROTECTIONS.map(p => (
            <div key={p.title} style={{
              background: '#fff', borderRadius: 14,
              border: '1px solid #e8ecf0',
              borderTop: `4px solid ${p.color}`,
              padding: '24px',
            }}>
              <div style={{ display: 'flex', gap: 14, alignItems: 'flex-start', marginBottom: 12 }}>
                <div>
                  <div style={{
                    fontSize: 10, fontWeight: 700, letterSpacing: 1.5, textTransform: 'uppercase',
                    color: p.color, marginBottom: 4,
                  }}>
                    {p.category}
                  </div>
                  <div style={{ fontWeight: 800, fontSize: 16, color: '#1a1a2e', lineHeight: 1.2 }}>{p.title}</div>
                </div>
              </div>
              <p style={{ fontSize: 13, color: '#555', lineHeight: 1.65, marginBottom: 12 }}>{p.desc}</p>
              <div style={{
                background: p.color + '10', borderLeft: `3px solid ${p.color}`,
                padding: '8px 12px', borderRadius: '0 6px 6px 0',
                fontSize: 12, color: p.color, fontWeight: 600, lineHeight: 1.4,
              }}>
                {p.protects}
              </div>
            </div>
          ))}
        </div>

        {/* SCENARIOS */}
        <h2 style={{ fontSize: 13, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', color: '#999', marginBottom: 24 }}>
          Real-World Scenarios: Before vs. After RO Tools
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, marginBottom: 64 }}>
          {SCENARIOS.map((s, i) => (
            <div key={s.scenario} style={{
              background: '#fff', borderRadius: 14,
              border: '1px solid #e8ecf0',
              overflow: 'hidden',
            }}>
              <div style={{
                background: NAVY, padding: '14px 24px',
                color: '#fff', fontWeight: 700, fontSize: 15,
                display: 'flex', alignItems: 'center', gap: 12,
              }}>
                <span style={{
                  background: RED, borderRadius: '50%', width: 26, height: 26,
                  display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 12, fontWeight: 800, flexShrink: 0,
                }}>{i + 1}</span>
                {s.scenario}
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr' }}>
                <div style={{ padding: '20px 24px', borderRight: '1px solid #f0f0f0' }}>
                  <div style={{
                    fontSize: 10, fontWeight: 800, letterSpacing: 1.5, textTransform: 'uppercase',
                    color: '#c0392b', marginBottom: 8,
                  }}>Without RO Tools</div>
                  <p style={{ fontSize: 13, color: '#555', lineHeight: 1.65, margin: 0 }}>{s.without}</p>
                </div>
                <div style={{ padding: '20px 24px', background: '#f8fffe' }}>
                  <div style={{
                    fontSize: 10, fontWeight: 800, letterSpacing: 1.5, textTransform: 'uppercase',
                    color: '#27ae60', marginBottom: 8,
                  }}>With RO Tools</div>
                  <p style={{ fontSize: 13, color: '#555', lineHeight: 1.65, margin: 0 }}>{s.with}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* INFRASTRUCTURE CALLOUT */}
        <div style={{
          background: `linear-gradient(135deg, #1a0a2e, #3d1a7a)`,
          borderRadius: 16, padding: '40px', color: '#fff', marginBottom: 56,
        }}>
          <h3 style={{ fontSize: 20, fontWeight: 800, marginBottom: 10 }}>Why Infrastructure Matters for Liability</h3>
          <p style={{ opacity: 0.85, lineHeight: 1.7, fontSize: 14, marginBottom: 24 }}>
            Liability protection is only as strong as the infrastructure behind it. Records stored on third-party SaaS platforms (Homebase, Jolt, Google Drive) are subject to vendor outages, data loss, and access revocation. If a vendor goes down during a legal discovery deadline, JMVG cannot produce records it doesn't control.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 16 }}>
            {[
              ['Google Cloud Storage', 'Immutable object storage — records cannot be deleted or modified'],
              ['Cloud Logging', 'Every action logged with user, store, IP, and timestamp'],
              ['Secret Manager', 'Zero plaintext credentials — no credential-exposure liability'],
              ['Cloud Run (99.9% SLA)', 'Records always accessible — no vendor-outage excuse'],
              ['JWT + PBKDF2 Auth', 'SHA-512 PIN hashing — no weak credential exposure'],
              ['JMVG Google Org', 'All data under @jmvalley.com — no third-party data custody'],
            ].map(([title, sub]) => (
              <div key={title} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 700 }}>{title}</div>
                  <div style={{ fontSize: 12, opacity: 0.65, marginTop: 2, lineHeight: 1.4 }}>{sub}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{ textAlign: 'center' }}>
          <a href="/security" style={{
            display: 'inline-block', background: '#c0392b', color: '#fff',
            padding: '14px 36px', borderRadius: 10, fontWeight: 700, fontSize: 15,
            textDecoration: 'none', marginRight: 12,
          }}>
            See Security Findings →
          </a>
          <a href="/welcome" style={{
            display: 'inline-block', background: '#f0f4f8', color: NAVY,
            padding: '14px 36px', borderRadius: 10, fontWeight: 700, fontSize: 15,
            textDecoration: 'none',
          }}>
            Back to Overview
          </a>
        </div>

        {/* FOOTER */}
        <div style={{ textAlign: 'center', color: '#aaa', fontSize: 12, marginTop: 64 }}>
          <div style={{ fontWeight: 700, marginBottom: 4, color: '#666' }}>JM Valley Group · Liability Protection Brief · April 2026</div>
          <div>Prepared by Christopher Ruzylo · Proprietary — not for external distribution</div>
        </div>
      </div>
    </div>
  );
}
