import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { getSession } from '@/lib/session';
import { loadJsonFile, loadJsonFileAsync, updateJsonFile } from '@/lib/data';
import { rateLimit } from '@/lib/rate-limit';

export const dynamic = 'force-dynamic';

function getStoreNumber(session) {
  const profiles = loadJsonFile('profiles.json');
  const profile = profiles[session.id];
  return profile?.storeNumber || null;
}

/**
 * GET /api/catering/orders — List orders for a client or all orders.
 * Query: clientId (optional), limit, offset
 */
export async function GET(request) {
  const session = getSession();
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const storeNumber = getStoreNumber(session);
  if (!storeNumber) return NextResponse.json({ error: 'No store configured' }, { status: 400 });

  const data = await loadJsonFileAsync(`catering-${storeNumber}.json`);
  let orders = Array.isArray(data.orders) ? data.orders : [];

  const { searchParams } = new URL(request.url);
  const clientId = searchParams.get('clientId');
  if (clientId) orders = orders.filter(o => o.clientId === clientId);

  orders.sort((a, b) => new Date(b.orderDate) - new Date(a.orderDate));

  const limit = Math.min(Math.max(parseInt(searchParams.get('limit')) || 50, 1), 200);
  const offset = Math.max(parseInt(searchParams.get('offset')) || 0, 0);

  return NextResponse.json({
    orders: orders.slice(offset, offset + limit),
    total: orders.length,
  });
}

/**
 * POST /api/catering/orders — Log a catering order.
 * Body: { clientId, orderDate, totalAmount, itemCount?, headCount?, notes?, autoGenerated? }
 *
 * If clientId is not provided but clientName is, auto-create or match client.
 */
export async function POST(request) {
  const { limited } = rateLimit('catering-orders', 60000, 30, request);
  if (limited) return NextResponse.json({ error: 'Too many requests' }, { status: 429 });

  const session = getSession();
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const storeNumber = getStoreNumber(session);
  if (!storeNumber) return NextResponse.json({ error: 'No store configured' }, { status: 400 });

  let body;
  try { body = await request.json(); } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (!body.totalAmount && body.totalAmount !== 0) {
    return NextResponse.json({ error: 'totalAmount is required' }, { status: 400 });
  }

  let clientId = body.clientId || null;
  let autoCreated = false;

  const result = await updateJsonFile(`catering-${storeNumber}.json`, (data) => {
    if (!data.clients) data.clients = [];
    if (!data.orders) data.orders = [];

    // Auto-create or match client if no clientId but clientName provided
    if (!clientId && body.clientName && body.clientName.trim()) {
      const name = body.clientName.trim().toLowerCase();
      const existing = data.clients.find(c =>
        c.clientName.toLowerCase() === name ||
        (body.companyName && c.companyName && c.companyName.toLowerCase() === body.companyName.trim().toLowerCase() && c.clientName.toLowerCase() === name)
      );
      if (existing) {
        clientId = existing.id;
        // Update contact info if provided and currently empty
        if (body.phone && !existing.phone) existing.phone = String(body.phone).trim().slice(0, 30);
        if (body.email && !existing.email) existing.email = String(body.email).trim().slice(0, 200);
        if (body.companyName && !existing.companyName) existing.companyName = String(body.companyName).trim().slice(0, 200);
        if (body.address && !existing.address) existing.address = String(body.address).trim().slice(0, 500);
        existing.updatedAt = new Date().toISOString();
      } else {
        // Create new client
        const newClient = {
          id: crypto.randomUUID(),
          clientName: String(body.clientName).trim().slice(0, 200),
          companyName: body.companyName ? String(body.companyName).trim().slice(0, 200) : '',
          phone: body.phone ? String(body.phone).trim().slice(0, 30) : '',
          email: body.email ? String(body.email).trim().slice(0, 200) : '',
          address: body.address ? String(body.address).trim().slice(0, 500) : '',
          notes: '',
          notableDates: [],
          reorderFrequency: '',
          createdBy: session.id,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        data.clients.push(newClient);
        clientId = newClient.id;
        autoCreated = true;
      }
    }

    const order = {
      id: crypto.randomUUID(),
      clientId,
      orderDate: body.orderDate || new Date().toISOString().split('T')[0],
      totalAmount: parseFloat(body.totalAmount) || 0,
      itemCount: parseInt(body.itemCount) || 0,
      headCount: parseInt(body.headCount) || 0,
      notes: body.notes ? String(body.notes).trim().slice(0, 2000) : '',
      autoGenerated: body.autoGenerated || false,
      createdBy: session.id,
      createdAt: new Date().toISOString(),
    };

    data.orders.push(order);
    return data;
  });

  return NextResponse.json({ success: true, clientId, autoCreated });
}
