import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { getSession } from '@/lib/session';
import { loadJsonFileAsync, updateJsonFile } from '@/lib/data';
import { rateLimit } from '@/lib/rate-limit';
import { DEMO_CATERING_ORDERS, DEMO_CATERING_CLIENTS, isDemo } from '@/lib/demo-data';
import { enforceSameOriginMutation } from '@/lib/request-origin';

export const dynamic = 'force-dynamic';

const normalize = s => s.toLowerCase().replace(/\s+/g, ' ').trim();

// Pipeline statuses for catering orders. Must be kept in sync with the
// catering-tracker UI. Legacy orders without a status default to 'confirmed'.
const PIPELINE_STATUSES = ['lead', 'quoted', 'confirmed', 'prepped', 'delivered', 'paid'];

function sanitizeItems(arr) {
  if (!Array.isArray(arr)) return [];
  return arr.slice(0, 50).map(it => {
    const name = String(it?.name || '').trim().slice(0, 200);
    const qty = Math.max(0, Math.min(10000, parseFloat(it?.qty) || 0));
    const unitPrice = Math.max(0, Math.min(100000, parseFloat(it?.unitPrice) || 0));
    return { name, qty, unitPrice };
  }).filter(it => it.name || it.qty || it.unitPrice);
}

async function getStoreNumber(session) {
  const profiles = await loadJsonFileAsync('profiles.json');
  const profile = profiles[session.id];
  const num = profile?.storeNumber || null;
  if (num && !/^\w{1,20}$/.test(num)) return null;
  return num;
}

/**
 * GET /api/catering/orders — List orders for a client or all orders.
 * Query: clientId (optional), limit, offset
 */
export async function GET(request) {
  const session = getSession();
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const clientId = searchParams.get('clientId');
  const enrich = searchParams.get('enrich') === '1';
  const limit = Math.min(Math.max(parseInt(searchParams.get('limit')) || 50, 1), 500);
  const offset = Math.max(parseInt(searchParams.get('offset')) || 0, 0);

  let orders;
  let clients;
  if (isDemo(session)) {
    orders = [...DEMO_CATERING_ORDERS];
    clients = DEMO_CATERING_CLIENTS || [];
  } else {
    const storeNumber = await getStoreNumber(session);
    if (!storeNumber) return NextResponse.json({ error: 'No store configured' }, { status: 400 });
    const data = await loadJsonFileAsync(`catering-${storeNumber}.json`);
    orders = Array.isArray(data.orders) ? [...data.orders] : [];
    clients = Array.isArray(data.clients) ? data.clients : [];
  }

  if (clientId) orders = orders.filter(o => o.clientId === clientId);
  // Sort by delivery date if present, otherwise orderDate.
  orders.sort((a, b) => {
    const ad = new Date(a.deliveryDate || a.orderDate);
    const bd = new Date(b.deliveryDate || b.orderDate);
    return bd - ad;
  });

  let result = orders.slice(offset, offset + limit);
  if (enrich) {
    const clientMap = new Map(clients.map(c => [c.id, c]));
    result = result.map(o => {
      const c = clientMap.get(o.clientId) || null;
      return {
        ...o,
        status: o.status || 'confirmed',
        // Fallback display fields from linked client if not on the order.
        customerName: o.customerName || c?.clientName || '',
        customerPhone: o.customerPhone || c?.phone || '',
        customerEmail: o.customerEmail || c?.email || '',
        deliveryAddress: o.deliveryAddress || c?.address || '',
        client: c ? { id: c.id, clientName: c.clientName, companyName: c.companyName } : null,
      };
    });
  }

  return NextResponse.json({ orders: result, total: orders.length });
}


/**
 * POST /api/catering/orders — Log a catering order.
 * Body: { clientId | clientName, orderDate, totalAmount, itemCount?, headCount?, notes?, autoGenerated? }
 *
 * If clientId is not provided but clientName is, auto-create or match client.
 */
export async function POST(request) {
  const originError = enforceSameOriginMutation(request);
  if (originError) return originError;

  const { limited } = rateLimit('catering-orders', 60000, 30, request);
  if (limited) return NextResponse.json({ error: 'Too many requests' }, { status: 429 });

  const session = getSession();
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  if (isDemo(session)) {
    return NextResponse.json({ success: true, demo: true });
  }

  const storeNumber = await getStoreNumber(session);
  if (!storeNumber) return NextResponse.json({ error: 'No store configured' }, { status: 400 });

  let body;
  try { body = await request.json(); } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  // Validate totalAmount
  const totalAmount = parseFloat(body.totalAmount);
  if (isNaN(totalAmount) || totalAmount < 0 || totalAmount > 1000000) {
    return NextResponse.json({ error: 'totalAmount must be a number between 0 and 1,000,000' }, { status: 400 });
  }

  // Require either clientId or clientName
  if (!body.clientId && (!body.clientName || !String(body.clientName).trim())) {
    return NextResponse.json({ error: 'Either clientId or clientName is required' }, { status: 400 });
  }

  // Validate orderDate format if provided
  const orderDate = body.orderDate ? String(body.orderDate).slice(0, 10) : new Date().toISOString().split('T')[0];
  if (!/^\d{4}-\d{2}-\d{2}$/.test(orderDate)) {
    return NextResponse.json({ error: 'orderDate must be YYYY-MM-DD format' }, { status: 400 });
  }

  let clientId = body.clientId || null;
  let autoCreated = false;
  let createdOrder = null;

  await updateJsonFile(`catering-${storeNumber}.json`, (data) => {
    if (!data.clients) data.clients = [];
    if (!data.orders) data.orders = [];

    // Auto-create or match client if no clientId but clientName provided
    if (!clientId && body.clientName && body.clientName.trim()) {
      const name = normalize(body.clientName);
      const existing = data.clients.find(c => normalize(c.clientName) === name);
      if (existing) {
        clientId = existing.id;
        // Backfill contact info if provided and currently empty
        if (body.phone && !existing.phone) existing.phone = String(body.phone).trim().slice(0, 30);
        if (body.email && !existing.email) existing.email = String(body.email).trim().slice(0, 200);
        if (body.companyName && !existing.companyName) existing.companyName = String(body.companyName).trim().slice(0, 200);
        if (body.address && !existing.address) existing.address = String(body.address).trim().slice(0, 500);
        existing.updatedAt = new Date().toISOString();
      } else {
        // Create new client
        const newClient = {
          id: crypto.randomUUID(),
          clientName: String(body.clientName).trim().slice(0, 200),
          companyName: body.companyName ? String(body.companyName).trim().slice(0, 200) : '',
          phone: body.phone ? String(body.phone).trim().slice(0, 30) : '',
          email: body.email ? String(body.email).trim().slice(0, 200) : '',
          address: body.address ? String(body.address).trim().slice(0, 500) : '',
          notes: '',
          notableDates: [],
          reorderFrequency: '',
          createdBy: session.id,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        data.clients.push(newClient);
        clientId = newClient.id;
        autoCreated = true;
      }
    }

    // Store form snapshot for reorder capability (only on auto-generated orders)
    let formSnapshot = null;
    if (body.autoGenerated === true && body.formSnapshot && typeof body.formSnapshot === 'object') {
      try {
        const snap = JSON.stringify(body.formSnapshot);
        if (snap.length <= 50000) formSnapshot = JSON.parse(snap);
      } catch (e) { console.debug('[catering/orders] Invalid formSnapshot skipped:', e); }
    }

    // Extended pipeline fields (all optional, backwards compatible).
    const status = PIPELINE_STATUSES.includes(body.status) ? body.status : 'confirmed';
    const items = sanitizeItems(body.items);
    const deliveryDate = /^\d{4}-\d{2}-\d{2}$/.test(body.deliveryDate || '') ? body.deliveryDate : orderDate;
    const deliveryTime = body.deliveryTime ? String(body.deliveryTime).trim().slice(0, 20) : '';
    const tax = Math.max(0, Math.min(100, parseFloat(body.tax) || 0));
    const subtotal = items.length
      ? items.reduce((s, it) => s + it.qty * it.unitPrice, 0)
      : Math.max(0, parseFloat(body.subtotal) || totalAmount);

    const order = {
      id: crypto.randomUUID(),
      clientId,
      orderDate,
      deliveryDate,
      deliveryTime,
      totalAmount,
      subtotal,
      tax,
      items,
      status,
      customerName: body.customerName ? String(body.customerName).trim().slice(0, 200) : '',
      customerPhone: body.customerPhone ? String(body.customerPhone).trim().slice(0, 30) : '',
      customerEmail: body.customerEmail ? String(body.customerEmail).trim().slice(0, 200) : '',
      deliveryAddress: body.deliveryAddress ? String(body.deliveryAddress).trim().slice(0, 500) : '',
      depositPaid: body.depositPaid === true,
      itemCount: items.length
        ? items.reduce((s, it) => s + it.qty, 0)
        : Math.max(0, parseInt(body.itemCount) || 0),
      headCount: Math.max(0, parseInt(body.headCount) || 0),
      notes: body.notes ? String(body.notes).trim().slice(0, 2000) : '',
      autoGenerated: body.autoGenerated === true,
      formSnapshot,
      createdBy: session.id,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    data.orders.push(order);
    createdOrder = order;
    return data;
  });

  return NextResponse.json({ success: true, clientId, autoCreated, order: createdOrder }, { status: 201 });
}
